version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_Sistema_Turnos
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_mysql_main
      MYSQL_USER: usuario_app
      MYSQL_PASSWORD: password_app
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:

