server:
  port: 8084

spring:
  application:
    name: notificaciones-service

  datasource:
    url: jdbc:postgresql://localhost:5432/notificacionesdb
    username: postgres
    password: tu_contraseña_aqui
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: optional:configserver:http://localhost:8888

  mail:
    host: smtp.gmail.com
    port: 587
    username: tu_email@gmail.com
    password: tu_contraseña_app
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service
