server:
  port: 8083

spring:
  application:
    name: ordenes-service

  datasource:
    url: jdbc:postgresql://postgres_ordenes:5432/ordenes_db
    username: ordenes_user
    password: ordenes_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: configserver:http://microservice-config:8888

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka

