server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sistema-Turnos/Config-Server---Sistema-Turnos.git
          clone-on-start: true
          default-label: master

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: false

#HEALTH CHECK
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics  # Endpoints de monitoreo
  endpoint:
    health:
      show-details: always